name: qersheen
description: A smart bank and wallet SMS tracker app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_sms_inbox: ^1.0.5
  intl: ^0.20.3
  notification_listener_service: ^1.0.0
  permission_handler: ^13.0.2
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#070A11"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
